# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestD():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_d(self):
    self.driver.get("https://login.feishu.cn/accounts/page/login?app_id=1&redirect_uri=https://a1lus6gqmr.feishu.cn/workplace/")
    self.driver.set_window_size(1344, 815)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-input\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-input\"]").send_keys("18612725214")
    self.driver.find_element(By.CSS_SELECTOR, ".ud__checkbox__input").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-next-btn\"]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-next-btn\"]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_elements(By.CSS_SELECTOR, ".ud__button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ud__button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-pwd-input\"]").send_keys("luoluo606709")
    self.driver.find_element(By.CSS_SELECTOR, ".ud__button > .universe-icon path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ud__button > .universe-icon path").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-pwd-next-btn\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".user-list-item:nth-child(1) .user-name").click()
  
