# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_login(self):
    self.driver.get("https://oat2bnw0ial.feishu.cn/workplace/")
    # //*[@class='switch-login-mode-box']/span
    self.driver.find_element(By.XPATH, "//*[@class='switch-login-mode-box']/span").click()
    # 输入手机号
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-input\"]").clear()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-input\"]").send_keys("13395466794")
    # 点击同意 ud__checkbox__input
    self.driver.find_element(By.CSS_SELECTOR, ".ud__checkbox__input").click()
    # 点击下一步
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-phone-next-btn\"]").click()
    time.sleep(1)
    # $x("//*[@class=\"base-tab-pane\"]/button")
    loginText = self.driver.find_element(By.XPATH, "//*[@class=\"base-tab-pane\"]/button").text
    # 如果是验证码登录，则点击密码登录按钮
    if loginText == "密码登录":
      self.driver.find_element(By.XPATH, "//*[@class=\"base-tab-pane\"]/button").click()
    time.sleep(1)
    # 跳转到密码登录页面
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-pwd-input\"]").send_keys("luoluo606709")
    # 点击下一步
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-pwd-next-btn\"]").click()
    # 页面跳转
    time.sleep(5)

    # 获取页面title 如果包含工作台，说明断言正常
    assert "工作台" in self.driver.page_source

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-pwd-next-btn\"]")

